rulebook.tex

When delivering a product, the robot now also needs to send the ID of
the order that the product belongs to.
This idea was discussed at TC meeting 2/19.

Also require the order ID in the delivery message

---

.circleci/config.yml
Makefile
rulebook.tex

1. Add a Makefile to
* build the rulebook by invoking `latexmk`
* run the latex linter `chktex` and make sure that there are no warnings
* check that the file is encoded with UTF-8 without BOM (this tests the build error in #15 and gives a more explicit error message)
* check that the maximum linewidth is 80
2. Adapt the rulebook to pass all the tests above
3. Add the tests to circleci so they are run automatically

Add latex linter, filetype, and max linewidth checks

---

.circleci/config.yml
Makefile

As suggested in #17, use a specific tag for the docker image used in the CircleCI build.
Also make the checks more verbose so the output isn't empty if every test passes.
This resolves #17.

Tag texlive version & be more verbose in checks

---

rulebook.tex

Added a sentence that clarifies that blocked zones of any machines must be reachable from any location on the field.

Clarified paragraph regarding access to blocked zones

---

rulebook.tex

Awarding 2 points for cap buffering at the CS.
The points will be deducted in case the machine gets broken or reset.

Award 2 points for buffering a cap in the CS

---

rulebook.tex

As discussed at today's TC meeting, we no longer want the gate to be part of the DS prepare message. We already have the order ID (since #1), therefore sending the gate is redundant.
Also remove some redundant information in the rulebook about DS preparation to avoid inconsistencies.

Remove gate from DS prepare message

---

rulebook.tex

For a competitive order, only the team that delivers first gets points for the delivery, the second team will not get any points.
Points for production steps are unaffected.
This resolves #4.

Add competitive orders

---

rulebook.tex

Introduce a timelimit in the markerless machine recoginition task, such that teams need to speed up their recognition algorithms. Also increased the number of available machines to 4 for faster teams.

Time limit and more zones/score for markerless machine recognition

---

.github/CODEOWNERS

We no longer use PR approvals as way of voting, therefore, there is no
need for the CODEOWNERS anymore. With the new workflow, it makes more
sense to request a review from someone specifically, not from the whole
TC.

github: remove CODEOWNERS

---

.gitignore

Add some common files to gitignore to avoid accidental commits containing those files, as in #13.

gitignore: ignore files generated by latexmk and vim's swap file

---

README.md
rulebook.tex

This updates the meta info for this year, in particular:
* authors of the rulebook
* TC members
* OC members
* Exec (which remained the same)
* Update introduction
* Update any reference to the year 2018

Update meta info for 2019

---

rulebook.tex

Simplify the rules around possible delivery and production windows, such that they can be clearly described now.
The new system is:
- 50% of products are of complexity C0 or C1, the other 50% are C2 or C3
- orders arrive according to a set pattern (every 90+x seconds, x in [-180,180]
- orders arrive between minute 3 and 16 (except for 2 standing orders)
- standing orders are one C0/C1 and one C2/C3, first ring being free of payment
- explicitly mention that color combinations of complex products are unique, e.g., it is impossible to "upgrade" a started C2 to a C3

Rework rules regarding order schedule

---

rulebook.tex

This PR introduces the unified tournament format of the RCLL, where teams need to qualify for the main track or stay in a challenge track.
In order to qualify teams need to solve one production challenge, I don't remember if we actually specified the qualification task so far. If you have a better idea, let me know.
I also removed the convoluted distinction between round-robin and playoff phase, where in the former actual game points were accumulated, while in the latter the ranking was determined based on the number of wins.
I also removed the technical challenge as we discussed.

Add 2022 tournament format

---

rulebook.tex

This was discussed last year as well and is also implemented in https://github.com/robocup-logistics/rcll-refbox/pull/119.
I just forgot to mention it in the rulebook itself.
Edit: i also found some formatting issues with a table in that section that i fixed as well

Mention that consecutive rings never share the same color

---

barcodes/barcode_generator.bash
barcodes/printable_barcodes.boilerplate.tex
barcodes/printable_barcodes.template.tex
rulebook.tex

The rulebook does not mention the barcode format yet. The barcodes we have on our workpieces are from the UPC-E standard. Assuming those are the correct ones, we should state that in the rulebook. Can anyone confirm this?

mention barcode format and remove wrong code height specification

---

rulebook.tex

During the last RoboCup event it occured that RS slides weren't emptied on time leading to overflow and a machine entering the broken state. To clarify responsibility, this rule change specifies that the replenishers are responsible for clearing the slides once three payments have been inserted.

Clarify responsibility of replenishers for clearing slides

---

rulebook.tex

The detailed specifications for the (outdated) Robotino 3 would have to be replaced with updated specs for the Robotino 4. However, these specs are well maintained by Festo Didactics on robotino.com and there is no additional value in re-distributing them through the appendix in the rulebook.

Replace detailed and outdated robotino specs with a reference

---

rulebook.tex

#77 mentions underspecification of the materials to hand-in in remote competitions. This suggested change adds details to the required materials based on the practical implementation of the rules in 2021.

Clarify rules for remote challenges and specify documents for submission

---

rulebook.tex

In RoboCup 2022, team Carologistics used cellular data for communication after explicit approval from the other teams. This is now codified, addressing #78.

Potentially allow other wireless communication methods

---

rulebook.tex

This PR introduces a few rule changes around the scoring and handling of early, normal and late deliveries.
The technical implementation is handled in https://github.com/robocup-logistics/rcll-refbox/pull/146.
1. The point scoring for mounting the last ring of a product is moved to become part of the regular delivery points. This does change the total points that orders achieve, it just simplifies the handling by treating scoring of ring payments equal independent to the order they belong to.
2. With the above change the amount of delivery points now varies depending on the complexity and allows us to punish the late delivery of workpieces more harshly (up to 75% of the delivery points, which is up to 75 points for a C3 product). Additionally, the gradual point deduction is spread over a …

Rework scoring on delivery

---

rulebook.tex

The description of machine downtime interactions and workpiece handling left room for interpretation, as noted in #34. This change reflects how things are effectively handled during real RCLL tournaments and clarifies related rules.

Add clarification to machine broken time

---

rulebook.tex

With the planned rule changes to penalize dropping of workpieces, the special order O0 was added to use the DS to remove workpieces from the game without point deduction. This PR adds information on this special order to the rulebook.

Add description of special order O0 to remove workpieces through the DS

---

rulebook.tex

This rule change adds the option for a fifth machine with an unknown location to the navigation challenge as an incentive to build robust sensing and navigation in uncertain environments, as suggested in #65.

Add unknown machine variation to navigation challenge

---

rulebook.tex

Discussed in #67. Dropping workpieces on the field is an action equivalent to dropping products or materials on the floor of a factory, which would require additional clean-up. While it can be convenient for teams to just drop workpieces, it should be penalized so that teams avoid such behavior and instead use alternatives like shelves, storage stations, ring payment slides or delivery stations.

Penalize the dropping of workpieces on the field

---

rulebook.tex

This PR rewrites the delivery rules in challenge games. As stated in #76 it is now also allowed to do the delivery to a delivery station. The old rule with dropping it in the starting zone is still there to reduce the amount of machines needed. But a team has to specify in advance which type of delivery it will be doing.

Rework of delivery in challenges

---

rulebook.tex

The KBSG no longer hosts mailing lists.

rulebook: switch to non-kbsg mailing lists

---

rulebook.tex

This change is implemented through https://github.com/robocup-logistics/rcll-refbox/pull/196.
Originally, the challange track fields were played on magenta-halve, because the refbox generated fields on magenta and mirrored them to cyan.
Machines for both teams were placed on top of eachother, so team cyan could play on the magenta halve.
There were 2 issues with this:
1. The field generation constraints were actually for team cyan and interpreted as team magenta machines causing errors regarding legal rotations for delivery stations.
2. Some participants prefer to not receive machine info for machines that are placed on top of eachother.
To address this, actually treat the generated field correctly as cyan field, mirror it to magenta regardless and therefore let teams divide whether to …

update description of challenge field to refbox changes

---

rulebook.tex

This PR includes a set of suggested rule changes for the 2025 season. 
**Changes:**
- general update of release date, summary of TC work, minor proofreading
- lifting of platform restrictions, update hardware rules to derive constraints from robotino
- update to navigation challenge, alternative mode with machine sides instead of zones
- update to regulations regarding machine failure to account for technical malfunction 
- ~~removing marker less detection challenge~~, should be re-made with major changes in 2026
- rephrasing motivation for open challenge
- update list of TC, OC, Exec Committee Members

Rule Changes for 2025
